FROM node:22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm i -g serve

RUN npm ci --legacy-peer-deps

COPY . .

COPY .env.production .env

RUN rm -rf node_modules package-lock.json && npm install && npm run build

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]